# Generated by Django 4.2.11 on 2026-04-02 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('cantidad_total', models.PositiveIntegerField(default=1, verbose_name='cantidad total')),
                ('cantidad_disponible', models.PositiveIntegerField(default=1, verbose_name='cantidad disponible')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('rentado', 'Rentado'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20, verbose_name='estado')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='inventario.categoria', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
                'ordering': ['nombre'],
            },
        ),
    ]
