# Generated by Django 4.2.11 on 2026-04-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0006_add_condicion_cargo_danos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='condicion_devolucion',
            field=models.CharField(blank=True, choices=[('bueno', 'Bueno — sin daños'), ('daños_menores', 'Daños menores'), ('inservible', 'Inservible / Pérdida total'), ('extraviado', 'Extraviado')], default='', max_length=20, verbose_name='condición al devolver'),
        ),
    ]
