# Generated by Django 4.2.11 on 2026-04-02 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('telefono', models.CharField(max_length=20, verbose_name='teléfono')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='dirección')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_vencimiento', models.DateField(verbose_name='fecha de vencimiento')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='fecha de devolución')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio (MXN)')),
                ('deposito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='depósito (MXN)')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('vencida', 'Vencida')], default='activa', max_length=20, verbose_name='estado')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentas', to='rentas.cliente', verbose_name='cliente')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentas', to='inventario.equipo', verbose_name='equipo')),
                ('registrada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
            ],
            options={
                'verbose_name': 'renta',
                'verbose_name_plural': 'rentas',
                'ordering': ['fecha_vencimiento'],
            },
        ),
    ]
